blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/
    about: Please ask and answer questions here
  - name: Telegram
    url: https://t.me/
    about: OasisSwap Official
